import type { FastifyInstance } from 'fastify';
import type { RagEngine } from '../rag/index.js';
import type { LLMAdapter } from '../adapters/index.js';
import { allow } from '../lib/rateLimit.js';
import { runAgentTurn } from '../agent/agent.js';

interface ChatBody {
  question?: string;
  lang?: 'en' | 'es';
}

/**
 * POST /api/chat
 * Headers: x-user-id, x-session-id (anonymous IDs generated by the client;
 *          memory and tracing are scoped to one session per user).
 * Body: { question: string, lang?: 'en' | 'es' }
 * Returns: { mode, answer, citations, traceId }
 *
 * The agent orchestrator (src/agent/agent.ts) handles planning, tools,
 * retrieval/grounding, memory, adaptation, tracing, and graceful failure.
 */
export function registerChatRoute(app: FastifyInstance, rag: RagEngine, llm: LLMAdapter): void {
  app.post<{ Body: ChatBody }>('/api/chat', async (req, reply) => {
    const ip = req.ip || 'unknown';
    if (!allow(ip)) {
      return reply.code(429).send({ error: 'Too many requests. Please wait a moment.' });
    }

    const question = (req.body?.question ?? '').toString().trim();
    const lang = req.body?.lang;
    if (!question) {
      return reply.code(400).send({ error: 'A non-empty "question" is required.' });
    }
    if (question.length > 1000) {
      return reply.code(400).send({ error: 'Question is too long (max 1000 characters).' });
    }

    // Anonymous identity: never an email or name; the client generates opaque IDs.
    const userId = (req.headers['x-user-id'] as string) || 'anonymous';
    const sessionId = (req.headers['x-session-id'] as string) || `ip-${ip}`;

    // runAgentTurn never throws: failures are traced and returned as safe messages.
    const result = await runAgentTurn({ question, lang, userId, sessionId }, rag, llm);
    return reply.send(result);
  });
}
